-- CREATE Database
CREATE DATABASE SCHOOL;

-- selecting datbase
USE SCHOOL;

-- creating table students 
CREATE TABLE STUDENTS(
     ID INT,
     NAME VARCHAR(30),
     CLASS TINYINT
);

-- Inserting values into tables 
INSERT INTO STUDENTS VALUES(101, 'RAM', 9);
INSERT INTO STUDENTS VALUES(102, 'RAVI', 10);

-- Inserting values by specifing the column names
INSERT INTO STUDENTS(NAME, ID, CLASS)
VALUES('SIVA' , 101, 9), ('SRINU' , 103 , 9);

-- SELECTING DATA FROM TABLE 
SELECT * FROM  STUDENTS;

-- ADD NEW COLUMN TO STUDENT TABLE 
-- ALTERING TABLE 
-- SYNTAX: ALTER TABLE TABLE_NAME ADD COLUMN COLUMN_NAME DATATYPE
ALTER TABLE STUDENTS ADD COLUMN AGE TINYINT;
SELECT *FROM STUDENTS; 

-- DELETE COLUMN 
-- DELETE CLASS COLUMN 
-- SYNTAX ALTER TABLE TABLE_NAME DROP COLUMN COLUMN_NAME;
ALTER TABLE STUDENTS DROP COLUMN CLASS; 
SELECT *FROM STUDENTS; 

-- DESCRIBE TABLE 
-- SYNTAX : DESCRIBE TABLE_NAME 
DESCRIBE STUDENTS;

-- CHANGE AGE COLUMN DATATYPE 
ALTER TABLE STUDENTS MODIFY COLUMN AGE INT;


