-- Create Database
CREATE DATABASE IF NOT EXISTS IT_COMPANY;

-- Select Database
USE IT_COMPANY;

-- Drop tables if already exist (prevents error while re-running)
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS DEPT;

-- Create DEPT Table
CREATE TABLE DEPT(
    DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(30) NOT NULL UNIQUE
);
-- Create EMPLOYEE Table
CREATE TABLE EMPLOYEE(
    EMP_ID INT AUTO_INCREMENT,
    NAME VARCHAR(40) NOT NULL,
    DEPT_ID INT NOT NULL,
    SALARY INT UNSIGNED,
    PRIMARY KEY (EMP_ID),
    FOREIGN KEY (DEPT_ID) REFERENCES DEPT(DEPT_ID)
);

-- Insert into DEPT
INSERT INTO DEPT(DEPT_ID, DEPT_NAME)
VALUES 
(1001,'IT'),
(1002,'HR'),
(1003,'SALES');

-- Insert into EMPLOYEE 
-- (Do NOT insert EMP_ID because it is AUTO_INCREMENT)
INSERT INTO EMPLOYEE(NAME, DEPT_ID, SALARY)
VALUES 
('Ram',1001,4000),
('Sai',1001,5000),
('Shiva',1001,6000),
('Vamika',1002,7000);

-- View Data
SELECT * FROM EMPLOYEE;