-- create new database datasets
CREATE DATABASE  IF NOT EXISTS DATASETS;

-- select database
USE DATASETS;

-- check table data 
USE DATASETS;
SELECT * FROM TIPS;

DESCRIBE TIPS;

-- CHANGE SMOKER, DAY AND TIME COLUMNS DATATYPE INTO VARCHAR 
ALTER TABLE TIPS MODIFY SMOKER VARCHAR(20);
ALTER TABLE TIPS MODIFY DAY VARCHAR(20);
DESCRIBE TIPS;

-- CHANGE SEX COLUMN NAME TO GENDER
-- ALTER TABLE TABLE_NAME RENAME COLUMN OLD_COL_NAME TO NEW_COL_NAME
ALTER TABLE TIPS RENAME COLUMN SEX TO GENDER; 
DESCRIBE TIPS;

ALTER TABLE TIPS MODIFY GENDER ENUM("MALE", "FEMALE"); 
DESCRIBE TIPS;

-- SLECTING SMOKER DATA 
SELECT SMOKER FROM TIPS;
SELECT DISTINCT SMOKER FROM TIPS; -- UNIQUE VALUES;

ALTER TABLE TIPS MODIFY SMOKER ENUM("YES", "NO");
DESCRIBE TIPS;

-- ADD NOT NULL CONSTRAINT TO SMOKER
ALTER TABLE TIPS MODIFY SMOKER ENUM('YES','NO') NOT NULL;
DESC TIPS;
DESCRIBE TIPS;

-- CHANGE SIZE DEFAULT VALUE INTO 1 
ALTER TABLE TIPS MODIFY SIZE INT  NOT NULL default 1;
DESC TIPS;
DESCRIBE TIPS;


-- SELECT RECORDS WHOSE SIZE IS 3
SELECT *  FROM TIPS WHERE SIZE = 3;

-- FIND MALE SMOKER RECORDS 
SELECT * FROM TIPS WHERE GENDER = 'MALE' AND SMOKER = 'YES';

-- FIND FEMALE NON - SMOKER RECORDS 
SELECT *FROM TIPS WHERE GENDER = "FEMALE" AND SMOKER = "NO";

-- FIND FRIDAY TOTAL BILL
SELECT TOTAL_BILL FROM TIPS WHERE DAY = "FRI";

-- SELECT TATALBILL AFTER GIVING 10% DISCOUNT ON TOTAL BILL
SELECT TOTAL_BILL, TOTAL_BILL - (TOTAL_BILL * 0.10) AS DISCOUNTED_BILL FROM TIPS;

-- FIND MALE CUSTOMERS MINIMUM AND MAXIMUM BILL
SELECT  MIN(TOTAL_BILL) AS MIN_BILL, MAX(TOTAL_BILL) AS MAX_BILL FROM TIPS WHERE GENDER = 'MALE';

-- RETURN SMOKER AND NON-SMOKERS COUNT
SELECT SMOKER, COUNT(*) AS COUNT FROM TIPS GROUP BY SMOKER;

-- RETURN FEMALE SMOKERS AND NON-SMOKERS COUNT
SELECT SMOKER, COUNT(*) AS COUNT FROM TIPS WHERE GENDER = 'FEMALE' GROUP BY SMOKER;

-- FIND TOTAL BILL OF DINNER TIME AS PER THE GENDER 
SELECT GENDER, SUM(TOTAL_BILL) AS TOTAL_BILL FROM TIPS WHERE TIME = 'Dinner' GROUP BY GENDER;
-- RETURN TOP 5 TOTAL BILLS
SELECT * FROM TIPS ORDER BY TOTAL_BILL DESC LIMIT 5;

-- RETURN ALL RECORDS AS PER THE TOTAL BILL IN DESCENDING ORDER
SELECT * FROM TIPS ORDER BY TOTAL_BILL DESC;




