-- Create Database
CREATE DATABASE IF NOT EXISTS IT_COMPANYY;

-- Select Database
USE IT_COMPANYY;

-- Drop tables if already exist
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS DEPT;

-- Create DEPT Table
CREATE TABLE DEPT(
    DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(30) NOT NULL UNIQUE
);

-- Create EMPLOYEE Table
CREATE TABLE EMPLOYEE(
    EMP_ID INT AUTO_INCREMENT,
    NAME VARCHAR(40) NOT NULL,
    DEPT_ID INT NOT NULL,
    SALARY INT UNSIGNED,
    PRIMARY KEY (EMP_ID),
    FOREIGN KEY (DEPT_ID) REFERENCES DEPT(DEPT_ID)
);

-- Insert into DEPT
INSERT INTO DEPT(DEPT_ID, DEPT_NAME)
VALUES 
(1001,'IT'),
(1002,'HR'),
(1003,'SALES');

-- Insert into EMPLOYEE 
INSERT INTO EMPLOYEE(NAME, DEPT_ID, SALARY)
VALUES 
('Ram',1001,4000),
('Sai',1001,5000),
('Shiva',1001,6000),
('Vamika',1002,7000);

-- View All Employees
SELECT * FROM EMPLOYEE;

-- SELECT IT EMPLOYEES
SELECT * FROM EMPLOYEE 
WHERE DEPT_ID = 1001;

-- SELECT NON IT EMPLOYEES
SELECT * FROM EMPLOYEE 
WHERE DEPT_ID != 1001;

-- SELECT HR AND SALES EMPLOYEES
SELECT * FROM EMPLOYEE 
WHERE DEPT_ID IN (1002,1003);

-- FIND EMPLOYEES WITH SALARY > 3500
SELECT * FROM EMPLOYEE 
WHERE SALARY > 3500;

-- FIND EMPLOYEES WITH SALARY <= 3500
SELECT * FROM EMPLOYEE 
WHERE SALARY <= 3500;

-- FIND TOTAL EMPLOYEE COUNT
SELECT COUNT(*) AS TOTAL_EMPLOYEES 
FROM EMPLOYEE;

-- FIND TOTAL SALARY SPEND PER MONTH
SELECT SUM(SALARY) AS TOTAL_SALARY_SPEND
FROM EMPLOYEE;

-- COUNT IT DEPARTMENT EMPLOYEES
SELECT COUNT(*) AS IT_EMP_COUNT
FROM EMPLOYEE
WHERE DEPT_ID = 1001;

-- COUNT NON IT EMPLOYEES
SELECT COUNT(*) AS NON_IT_EMP_COUNT
FROM EMPLOYEE
WHERE DEPT_ID != 1001;

-- UPDATE SALARY 5000 FOR ALL EMPLOYESS 
SET SQL_SAFE_UPDATES = 0;
UPDATE EMPLOYEE SET SALARY = SALARY + 5000;

-- UPDATE 2000  FOR IT EMPLOYEES
UPDATE EMPLOYEE SET SALARY = SALARY + 2000 WHERE DEPT_ID = 1001;

-- DELETE 102 EMPLOYEE ID FROM EMPLOYEE TABLE 
-- DELETE FROM TABLE_ NAME 
-- WHERE CONDITION; 
DELETE FROM EMPLOYEE WHERE EMP_ID = 102;
SELECT *FROM EMPLOYEE;

-- FIND EMP DETAILS THOSE NAME STARTS WITH 'S'
SELECT * FROM EMPLOYEE
WHERE NAME LIKE 'S%'; 

-- FIND EMPLOYEE DETAILS THOSE NAME STARTS WITH 'I'
SELECT * FROM EMPLOYEE
WHERE NAME LIKE 'I%';

-- FIND EMPLOYEE DETAILS THOSE NAME CONTAINS 'A'
SELECT * FROM EMPLOYEE
WHERE NAME LIKE '%A%';